smart-escrow-test-deployment
BuilderOSS/nouns-builder-staging pull request #2
Opened 2024-11-05 15:26 UTC by wtfsayo

## Description

## Motivation & context

## Code review

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have done a self-review of my own code
- [ ] Any new and existing tests pass locally with my changes
- [ ] My changes generate no new warnings (lint warnings, console warnings, etc)

2024-11-08 13:09 UTC, wtfsayo commented
Can you share the logs @0xMillz

2024-11-08 15:55 UTC, 0xMillz commented
> Can you share the logs @0xMillz

Let me take a look. I thought I set them to be public

2024-11-08 16:00 UTC, 0xMillz commented
> Can you share the logs @0xMillz

Here's a screenshot for now. At first glance I think the fix would be to run `pnpm install` to get the lockfile up-to-date
<img width="1184" alt="Screenshot 2024-11-08 at 9 59 56 AM" src="https://github.com/user-attachments/assets/bd324935-e419-4ee7-9a57-9164e06e48c0">

2024-12-11 06:10 UTC, 0xMillz requested changes

2024-12-11 06:10 UTC, 0xMillz commented on apps/web/src/constants/rpc.ts
> +const TENDERYLY_RPC_KEY = process.env.NEXT_PUBLIC_TENDERLY_RPC_KEY ?? ''
`TENDERYLY` is spelled incorrectly

2024-12-11 06:10 UTC, 0xMillz commented on apps/web/src/constants/rpc.ts
> +const TENDERYLY_RPC_KEY = process.env.NEXT_PUBLIC_TENDERLY_RPC_KEY ?? ''
Also my goal is to ultimately remove this as a `NEXT_PUBLIC` env var because it should be a secret. But this is ok for now

2025-01-04 00:43 UTC, 0xMillz requested changes
A 40 file PR with 99 commits is way, way too big for a solid, honest code review. So I can't review this in it's current state. Bugs are almost for sure. I've been told the same by others when I was younger and learning then also learned from experience. I love our jobs, but to be albe to review a code change this huge, this complex, and also with all the money that could potentially flow through it--for me to review and potentially approve, this HUGE feature needs to be delivered in smaller, non-breaking pieces. We could also utilize feature flags. But I do not feel comfortable approving this yet. And sorry if my words accidently seem harsh. Ultimately this effects real people, with real money, and I would only like to spprove these code chsnges in individual chunks. It's the Agile style, mixed with a little bit of TDD. Much respect.

2025-01-05 11:53 UTC, scottrepreneur commented on apps/web/src/services/abiService.ts
> +      `https://api.etherscan.io/v2/api?chainid=${chainId}&module=contract&action=getabi&address=${fetchedAddress}&tag=latest&apikey=${process.env.ETHERSCAN_API_KEY}`
hardcode

2025-01-05 12:37 UTC, wtfsayo commented on apps/web/src/services/abiService.ts
> +      `https://api.etherscan.io/v2/api?chainid=${chainId}&module=contract&action=getabi&address=${fetchedAddress}&tag=latest&apikey=${process.env.ETHERSCAN_API_KEY}`
v2 api is single url for all chains

2025-01-08 11:15 UTC, closed without merging